if(process.env.NODE_ENV === "production"){
  module.exports = {
  	USER_LOGIN : process.env.USER_LOGIN,
  	USER_PASS : process.env.USER_PASS,
  	EMAIL_USERNAME: process.env.EMAIL_USERNAME,
  	EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
    NAME_CLOUDINARY : process.env.NAME_CLOUDINARY,
    API_KEY_CLOUDINARY: process.env.API_KEY_CLOUDINARY,
    API_SECRET_CLOUDINARY: process.env.API_SECRET_CLOUDINARY
  }
}else{ 
  const {USER_LOGIN, USER_PASS, EMAIL_USERNAME, EMAIL_PASSWORD, NAME_CLOUDINARY, API_KEY_CLOUDINARY, API_SECRET_CLOUDINARY} = require("./passwords_local");	
  module.exports = {
  	USER_LOGIN : USER_LOGIN,
  	USER_PASS : USER_PASS,
  	EMAIL_USERNAME: EMAIL_USERNAME,
  	EMAIL_PASSWORD: EMAIL_PASSWORD,
    NAME_CLOUDINARY : NAME_CLOUDINARY,
    API_KEY_CLOUDINARY: API_KEY_CLOUDINARY,
    API_SECRET_CLOUDINARY: API_SECRET_CLOUDINARY
  }
}
